// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentStatus():Promise<main.AgentStatus>;

export function GetSettings():Promise<main.Settings>;

export function KeyDown(arg1:string):Promise<void>;

export function KeyUp(arg1:string):Promise<void>;

export function Load(arg1:string):Promise<void>;

export function Play():Promise<void>;

export function ReleaseAll():Promise<void>;

export function Reset():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function Setup():Promise<main.Setup>;

export function StartAgent():Promise<main.AgentStatus>;

export function StopAgent():Promise<main.AgentStatus>;

export function TestAgent(arg1:main.Settings):Promise<string>;

export function TogglePause():Promise<boolean>;
