// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentStatus() {
  return window['go']['main']['App']['AgentStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function KeyDown(arg1) {
  return window['go']['main']['App']['KeyDown'](arg1);
}

export function KeyUp(arg1) {
  return window['go']['main']['App']['KeyUp'](arg1);
}

export function Load(arg1) {
  return window['go']['main']['App']['Load'](arg1);
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function ReleaseAll() {
  return window['go']['main']['App']['ReleaseAll']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function Setup() {
  return window['go']['main']['App']['Setup']();
}

export function StartAgent() {
  return window['go']['main']['App']['StartAgent']();
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function TestAgent(arg1) {
  return window['go']['main']['App']['TestAgent'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
